name: Release

on:
  push:
    branches: [main]

jobs:
  publish-worlds:
    runs-on: ${{ matrix.runner-os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            runner-os: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.2.0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install packages
        run: bun install

      - name: Compile worlds
        run: bun run scripts/compileWorlds.ts

      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@v6.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          tag_template: "yyyy.mm.dd.i"

      - name: Release worlds
        uses: softprops/action-gh-release@v1
        with:
          name: Worlds
          tag_name: ${{ steps.generate_release_tag.outputs.next_release_tag }}
          files: worlds.json
          generate_release_notes: true
          draft: false
