name: Release

on:
  push:
    branches: [main]

jobs:
  publish-worlds:
    runs-on: ${{ matrix.runner-os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Linux
            runner-os: ubuntu-latest

    steps:
      - uses: CompeyDev/setup-rokit@v0.1.0
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Install Toolchain
        run: rokit install --no-trust-check

      - name: Run test runner
        run: lune run utils/PublishToRoblox.luau -- --auth ${{ secrets.ROBLOSECURITY }}
